name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - ci_testing
  pull_request:

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo aaa
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
          registry: ghcr.io
          image: epicgames/unreal-engine:dev-slim-5.0
          options: --user root
          run: |
            chown -R ue4 ${GITHUB_WORKSPACE}/
            sudo -u ue4 -H /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun \
              -utf8output \
              -platform=Linux \
              -clientconfig=Shipping \
              -serverconfig=Shipping \
              -project=${GITHUB_WORKSPACE}/MyUECppProject/MyUECppProject.uproject \
              -noP4 \
              -nodebuginfo \
              -allmaps \
              -cook \
              -build \
              -stage \
              -prereqs \
              -pak \
              -archive \
              -archivedirectory=/tmp/Packaged